-- MySQL Script generated by MySQL Workbench
-- Thu Mar 13 21:02:06 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`servicios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`servicios` (
  `servicio_id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `precio` INT NULL,
  PRIMARY KEY (`servicio_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`paquetes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`paquetes` (
  `paquete_id` INT NOT NULL AUTO_INCREMENT,
  `servicio` VARCHAR(50) NOT NULL,
  `precio` INT NOT NULL,
  PRIMARY KEY (`paquete_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`servicios_paquetes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`servicios_paquetes` (
  `servicio_id` INT NOT NULL AUTO_INCREMENT,
  `paquete_id` INT NOT NULL,
  PRIMARY KEY (`servicio_id`),
  INDEX `paquete_id_idx` (`paquete_id` ASC) VISIBLE,
  CONSTRAINT `servicio_paquetes_servicio_id`
    FOREIGN KEY (`servicio_id`)
    REFERENCES `mydb`.`servicios` (`servicio_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `servicio_paquetes_paquete_id`
    FOREIGN KEY (`paquete_id`)
    REFERENCES `mydb`.`paquetes` (`paquete_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pacientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pacientes` (
  `paciente_id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NULL,
  `apellido` VARCHAR(50) NULL,
  `dni` INT NULL,
  `fecha_nacimiento` DATETIME NOT NULL,
  `email` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  PRIMARY KEY (`paciente_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`medicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`medicos` (
  `medico_id` INT NOT NULL AUTO_INCREMENT,
  `especialidad` VARCHAR(45) NULL,
  `turnos_disponibles` INT NULL,
  `sueldo` INT NULL,
  `paciente_id` INT NOT NULL,
  PRIMARY KEY (`medico_id`),
  INDEX `paciente_id_idx` (`paciente_id` ASC) VISIBLE,
  CONSTRAINT `medicos_paciente_id`
    FOREIGN KEY (`paciente_id`)
    REFERENCES `mydb`.`pacientes` (`paciente_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`turnos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`turnos` (
  `turno_id` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NOT NULL,
  `hora` VARCHAR(50) NOT NULL,
  `paciente_id` INT NOT NULL,
  `medico_id` INT NOT NULL,
  `paquete_id` INT NOT NULL,
  `monto_total` INT NULL,
  `pago` VARCHAR(45) NULL,
  PRIMARY KEY (`turno_id`),
  INDEX `paciente_id_idx` (`paciente_id` ASC) VISIBLE,
  INDEX `medico_id_idx` (`medico_id` ASC) VISIBLE,
  INDEX `paquete_id_idx` (`paquete_id` ASC) VISIBLE,
  CONSTRAINT `turnos_paciente_id`
    FOREIGN KEY (`paciente_id`)
    REFERENCES `mydb`.`pacientes` (`paciente_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `turnos_medico_id`
    FOREIGN KEY (`medico_id`)
    REFERENCES `mydb`.`medicos` (`medico_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `turnos_paquete_id`
    FOREIGN KEY (`paquete_id`)
    REFERENCES `mydb`.`paquetes` (`paquete_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
